name: DooIT
description: "A simple budget management Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pie_chart: ^5.0.0  # Untuk statistik pengeluaran  
  intl: ^0.18.0  # Untuk format angka dalam Rupiah
  country_flags: ^3.0.0
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  svg_flag: ^1.5.1
  flag: ^7.0.0
  phosphor_flutter: ^2.1.0 # Untuk ikon navigasi
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  shimmer: ^3.0.0
  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - .env

flutter_icons:
  android: true
  image_path: "assets/images/logo1.png"